version: '2'
services:
  web:
    build:
      context: ./angulara-back-end
      dockerfile: web.docker
    volumes:
      - ./angulara-back-end:/var/www
    ports:
      - 8080:80
    links:
      - app
  app:
    container_name: laraangu
    build:
      context: ./angulara-back-end
      dockerfile: app.docker
    volumes:
      - ./angulara-back-end:/var/www
    links:
      - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  database:
    image: mysql:5.6
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=dockerApp"
    ports:
        - "33061:3306"
  angular:
    container_name: angular
    command: "npm start -- --host=0.0.0.0"
    build: ./angulara-front-end
    volumes: 
      - ./angulara-front-end:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"
